package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CentroComercial generated by hbm2java
 */
public class CentroComercial  implements java.io.Serializable {


     private CentroComercialId id;
     private String administrador;
     private Date horarioApertura;
     private Date horarioCierre;
     private byte[] imagen;
     private String telefono;
     private String sitioWeb;

    public CentroComercial() {
    }

	
    public CentroComercial(CentroComercialId id, String administrador, Date horarioApertura, Date horarioCierre, byte[] imagen) {
        this.id = id;
        this.administrador = administrador;
        this.horarioApertura = horarioApertura;
        this.horarioCierre = horarioCierre;
        this.imagen = imagen;
    }
    public CentroComercial(CentroComercialId id, String administrador, Date horarioApertura, Date horarioCierre, byte[] imagen, String telefono, String sitioWeb) {
       this.id = id;
       this.administrador = administrador;
       this.horarioApertura = horarioApertura;
       this.horarioCierre = horarioCierre;
       this.imagen = imagen;
       this.telefono = telefono;
       this.sitioWeb = sitioWeb;
    }
   
    public CentroComercialId getId() {
        return this.id;
    }
    
    public void setId(CentroComercialId id) {
        this.id = id;
    }
    public String getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(String administrador) {
        this.administrador = administrador;
    }
    public Date getHorarioApertura() {
        return this.horarioApertura;
    }
    
    public void setHorarioApertura(Date horarioApertura) {
        this.horarioApertura = horarioApertura;
    }
    public Date getHorarioCierre() {
        return this.horarioCierre;
    }
    
    public void setHorarioCierre(Date horarioCierre) {
        this.horarioCierre = horarioCierre;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getSitioWeb() {
        return this.sitioWeb;
    }
    
    public void setSitioWeb(String sitioWeb) {
        this.sitioWeb = sitioWeb;
    }




}


