package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1



/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private LocalId id;
     private String area;
     private char estatus;

    public Local() {
    }

    public Local(LocalId id, String area, char estatus) {
       this.id = id;
       this.area = area;
       this.estatus = estatus;
    }
   
    public LocalId getId() {
        return this.id;
    }
    
    public void setId(LocalId id) {
        this.id = id;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public char getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(char estatus) {
        this.estatus = estatus;
    }




}


