package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1

import utilerias.Mysql;




/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private AreaId id;
     private double latitud;
     private double longitud;
     private byte[] imagen;

    public Area() {
        latitud = Mysql.valorNoSeteadoDouble;
        longitud = Mysql.valorNoSeteadoDouble;
    }

    public Area(AreaId id, double latitud, double longitud, byte[] imagen) {
       this.id = id;
       this.latitud = latitud;
       this.longitud = longitud;
       this.imagen = imagen;
    }
   
    public AreaId getId() {
        return this.id;
    }
    
    public void setId(AreaId id) {
        this.id = id;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }

    @Override
    public String toString(){
        return this.id.getNombre();
    }


}


