package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1

import utilerias.Mysql;




/**
 * CodigoPostal generated by hbm2java
 */
public class CodigoPostal  implements java.io.Serializable {


     private Integer id;
     private int codigo;
     private String estado;
     private String municipio;
     private String asentamiento;

    public CodigoPostal() {
        id = Mysql.valorNoSeteadoInt;
        codigo = Mysql.valorNoSeteadoInt;
    }

    public CodigoPostal(int codigo, String estado, String municipio, String asentamiento) {
       this.codigo = codigo;
       this.estado = estado;
       this.municipio = municipio;
       this.asentamiento = asentamiento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getAsentamiento() {
        return this.asentamiento;
    }
    
    public void setAsentamiento(String asentamiento) {
        this.asentamiento = asentamiento;
    }




}


