package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1

import utilerias.Mysql;




/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer id;
     private int codigoPostal;
     private String calle;
     private int numeroExterior;
     private Integer numeroInterior;

    public Direccion() {
        id = Mysql.valorNoSeteadoInt;
        codigoPostal = Mysql.valorNoSeteadoInt;
        numeroExterior = Mysql.valorNoSeteadoInt;
        numeroInterior = Mysql.valorNoSeteadoInt;
    }

	
    public Direccion(int codigoPostal, String calle, int numeroExterior) {
        this.codigoPostal = codigoPostal;
        this.calle = calle;
        this.numeroExterior = numeroExterior;
    }
    public Direccion(int codigoPostal, String calle, int numeroExterior, Integer numeroInterior) {
       this.codigoPostal = codigoPostal;
       this.calle = calle;
       this.numeroExterior = numeroExterior;
       this.numeroInterior = numeroInterior;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(int codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public int getNumeroExterior() {
        return this.numeroExterior;
    }
    
    public void setNumeroExterior(int numeroExterior) {
        this.numeroExterior = numeroExterior;
    }
    public Integer getNumeroInterior() {
        return this.numeroInterior;
    }
    
    public void setNumeroInterior(Integer numeroInterior) {
        this.numeroInterior = numeroInterior;
    }




}


