package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private OfertaId id;
     private Date inicio;
     private Date expiracion;
     private byte[] imagen;

    public Oferta() {
    }

    public Oferta(OfertaId id, Date inicio, Date expiracion, byte[] imagen) {
       this.id = id;
       this.inicio = inicio;
       this.expiracion = expiracion;
       this.imagen = imagen;
    }
   
    public OfertaId getId() {
        return this.id;
    }
    
    public void setId(OfertaId id) {
        this.id = id;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getExpiracion() {
        return this.expiracion;
    }
    
    public void setExpiracion(Date expiracion) {
        this.expiracion = expiracion;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }




}


