package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1

import utilerias.Mysql;




/**
 * OfertaId generated by hbm2java
 */
public class OfertaId  implements java.io.Serializable {


     private String descripcion;
     private String local;
     private String centroComercial;
     private int direccionCentroComercial;
     private String locatario;

    public OfertaId() {
        direccionCentroComercial = Mysql.valorNoSeteadoInt;
    }

    public OfertaId(String descripcion, String local, String centroComercial, int direccionCentroComercial, String locatario) {
       this.descripcion = descripcion;
       this.local = local;
       this.centroComercial = centroComercial;
       this.direccionCentroComercial = direccionCentroComercial;
       this.locatario = locatario;
    }
   
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getCentroComercial() {
        return this.centroComercial;
    }
    
    public void setCentroComercial(String centroComercial) {
        this.centroComercial = centroComercial;
    }
    public int getDireccionCentroComercial() {
        return this.direccionCentroComercial;
    }
    
    public void setDireccionCentroComercial(int direccionCentroComercial) {
        this.direccionCentroComercial = direccionCentroComercial;
    }
    public String getLocatario() {
        return this.locatario;
    }
    
    public void setLocatario(String locatario) {
        this.locatario = locatario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfertaId) ) return false;
		 OfertaId castOther = ( OfertaId ) other; 
         
		 return ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getLocal()==castOther.getLocal()) || ( this.getLocal()!=null && castOther.getLocal()!=null && this.getLocal().equals(castOther.getLocal()) ) )
 && ( (this.getCentroComercial()==castOther.getCentroComercial()) || ( this.getCentroComercial()!=null && castOther.getCentroComercial()!=null && this.getCentroComercial().equals(castOther.getCentroComercial()) ) )
 && (this.getDireccionCentroComercial()==castOther.getDireccionCentroComercial())
 && ( (this.getLocatario()==castOther.getLocatario()) || ( this.getLocatario()!=null && castOther.getLocatario()!=null && this.getLocatario().equals(castOther.getLocatario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getLocal() == null ? 0 : this.getLocal().hashCode() );
         result = 37 * result + ( getCentroComercial() == null ? 0 : this.getCentroComercial().hashCode() );
         result = 37 * result + this.getDireccionCentroComercial();
         result = 37 * result + ( getLocatario() == null ? 0 : this.getLocatario().hashCode() );
         return result;
   }   


}


