package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import utilerias.Mysql;

/**
 * RegistroLocatario generated by hbm2java
 */
public class RegistroLocatario  implements java.io.Serializable {


     private String cuenta;
     private String local;
     private String centroComercial;
     private int direccionCentroComercial;
     private String clave;
     private String nombres;
     private String primerApellido;
     private String segundoApellido;
     private byte[] imagen;
     private String nombreLocal;
     private String giro;
     private Date horarioApertura;
     private Date horarioCierre;
     private String telefono;
     private String sitioWeb;
     private byte[] imagenLocal;

    public RegistroLocatario() {
        direccionCentroComercial = Mysql.valorNoSeteadoInt;
    }

	
    public RegistroLocatario(String cuenta, String local, String centroComercial, int direccionCentroComercial, String clave, String nombres, String primerApellido, String segundoApellido, byte[] imagen, String nombreLocal, String giro, Date horarioApertura, Date horarioCierre, byte[] imagenLocal) {
        this.cuenta = cuenta;
        this.local = local;
        this.centroComercial = centroComercial;
        this.direccionCentroComercial = direccionCentroComercial;
        this.clave = clave;
        this.nombres = nombres;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.imagen = imagen;
        this.nombreLocal = nombreLocal;
        this.giro = giro;
        this.horarioApertura = horarioApertura;
        this.horarioCierre = horarioCierre;
        this.imagenLocal = imagenLocal;
    }
    public RegistroLocatario(String cuenta, String local, String centroComercial, int direccionCentroComercial, String clave, String nombres, String primerApellido, String segundoApellido, byte[] imagen, String nombreLocal, String giro, Date horarioApertura, Date horarioCierre, String telefono, String sitioWeb, byte[] imagenLocal) {
       this.cuenta = cuenta;
       this.local = local;
       this.centroComercial = centroComercial;
       this.direccionCentroComercial = direccionCentroComercial;
       this.clave = clave;
       this.nombres = nombres;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.imagen = imagen;
       this.nombreLocal = nombreLocal;
       this.giro = giro;
       this.horarioApertura = horarioApertura;
       this.horarioCierre = horarioCierre;
       this.telefono = telefono;
       this.sitioWeb = sitioWeb;
       this.imagenLocal = imagenLocal;
    }
   
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getCentroComercial() {
        return this.centroComercial;
    }
    
    public void setCentroComercial(String centroComercial) {
        this.centroComercial = centroComercial;
    }
    public int getDireccionCentroComercial() {
        return this.direccionCentroComercial;
    }
    
    public void setDireccionCentroComercial(int direccionCentroComercial) {
        this.direccionCentroComercial = direccionCentroComercial;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public String getNombreLocal() {
        return this.nombreLocal;
    }
    
    public void setNombreLocal(String nombreLocal) {
        this.nombreLocal = nombreLocal;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }
    public Date getHorarioApertura() {
        return this.horarioApertura;
    }
    
    public void setHorarioApertura(Date horarioApertura) {
        this.horarioApertura = horarioApertura;
    }
    public Date getHorarioCierre() {
        return this.horarioCierre;
    }
    
    public void setHorarioCierre(Date horarioCierre) {
        this.horarioCierre = horarioCierre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getSitioWeb() {
        return this.sitioWeb;
    }
    
    public void setSitioWeb(String sitioWeb) {
        this.sitioWeb = sitioWeb;
    }
    public byte[] getImagenLocal() {
        return this.imagenLocal;
    }
    
    public void setImagenLocal(byte[] imagenLocal) {
        this.imagenLocal = imagenLocal;
    }




}


