package modelo.basedatos;
// Generated Nov 12, 2016 10:26:48 PM by Hibernate Tools 4.3.1



/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private ServicioId id;
     private String descripcion;
     private byte[] imagen;

    public Servicio() {
    }

    public Servicio(ServicioId id, String descripcion, byte[] imagen) {
       this.id = id;
       this.descripcion = descripcion;
       this.imagen = imagen;
    }
   
    public ServicioId getId() {
        return this.id;
    }
    
    public void setId(ServicioId id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }




}


